# Generated by Django 6.0.4 on 2026-05-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Realisations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoprojet',
            name='description',
        ),
        migrations.AddField(
            model_name='projet',
            name='affiche',
            field=models.ImageField(default='', upload_to='projet/affiche/'),
            preserve_default=False,
        ),
    ]
