# Generated by Django 6.0.4 on 2026-07-11 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Realisations', '0002_remove_photoprojet_description_projet_affiche'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projet',
            options={'ordering': ['-date_creation']},
        ),
    ]
