# Generated by Django 6.0.4 on 2026-05-10 17:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2022)])),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='gallery',
        ),
        migrations.CreateModel(
            name='ImagesEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gallery.edition')),
            ],
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
