# Generated by Django 6.0.4 on 2026-07-11 12:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0002_edition_remove_image_gallery_imagesedition_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edition',
            options={'ordering': ['-annee']},
        ),
        migrations.AlterField(
            model_name='edition',
            name='annee',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(2022)]),
        ),
        migrations.AlterField(
            model_name='imagesedition',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Gallery.edition'),
        ),
    ]
