# Generated by Django 6.0.4 on 2026-05-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoservice',
            name='prix',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='prix',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
