# Generated by Django 6.0.4 on 2026-05-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_photoservice_prix_service_prix'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photoservice',
            old_name='prix',
            new_name='prix_autre',
        ),
        migrations.AddField(
            model_name='photoservice',
            name='prix_nord_kivu',
            field=models.IntegerField(default=0),
        ),
    ]
