# Generated by Django 6.0.4 on 2026-05-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0003_rename_prix_photoservice_prix_autre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoservice',
            name='prix_autre',
        ),
        migrations.RemoveField(
            model_name='photoservice',
            name='prix_nord_kivu',
        ),
        migrations.AddField(
            model_name='service',
            name='prix_autre',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='prix_nord_kivu',
            field=models.IntegerField(default=0),
        ),
    ]
