# Generated by Django 6.0.4 on 2026-05-01 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0004_remove_photoservice_prix_autre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='prix',
        ),
    ]
