# Generated by Django 6.0.4 on 2026-05-14 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0005_remove_service_prix'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='prix_autre',
            new_name='prix',
        ),
        migrations.RemoveField(
            model_name='service',
            name='prix_nord_kivu',
        ),
    ]
