# Generated by Django 6.0.4 on 2026-05-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0006_rename_prix_autre_service_prix_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='prix',
        ),
        migrations.AddField(
            model_name='service',
            name='pricing',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
