# Generated by Django 6.0.4 on 2026-07-11 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0007_remove_service_prix_service_pricing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['nom']},
        ),
    ]
