# Generated by Django 6.0 on 2025-12-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(max_length=1000)),
                ('duree', models.DurationField(help_text='Durée de la formation (HH:MM:SS)')),
                ('prix', models.PositiveIntegerField(help_text='Prix en dollars')),
                ('affiche', models.ImageField(blank=True, null=True, upload_to='formation_images')),
                ('objectifs', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'ordering': ['nom'],
            },
        ),
    ]
