# Generated by Django 6.0 on 2025-12-21 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Formation', '0002_inscription'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inscription',
            unique_together={('formation', 'email')},
        ),
    ]
