# Generated by Django 6.0.4 on 2026-05-01 13:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formation', '0003_alter_inscription_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='logo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='logo'),
            preserve_default=False,
        ),
    ]
