# Generated by Django 6.0.4 on 2026-05-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formation', '0004_formation_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='prix',
        ),
        migrations.AddField(
            model_name='formation',
            name='prix_etudiant',
            field=models.PositiveBigIntegerField(default=0, help_text='Prix étudiant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formation',
            name='prix_pro',
            field=models.PositiveIntegerField(default=15, help_text='Prix pro'),
            preserve_default=False,
        ),
    ]
