# Generated by Django 6.0.4 on 2026-05-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formation', '0005_remove_formation_prix_formation_prix_etudiant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='duree',
            field=models.PositiveBigIntegerField(),
        ),
    ]
