# Generated by Django 6.0.4 on 2026-05-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formation', '0006_alter_formation_duree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='prix_etudiant',
            field=models.PositiveBigIntegerField(blank=True, help_text='Prix étudiant'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='prix_pro',
            field=models.PositiveIntegerField(blank=True, help_text='Prix pro'),
        ),
    ]
