# Generated by Django 6.0.4 on 2026-05-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formation', '0007_alter_formation_prix_etudiant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='prix_etudiant',
            field=models.PositiveBigIntegerField(blank=True, help_text='Prix étudiant', null=True),
        ),
        migrations.AlterField(
            model_name='formation',
            name='prix_pro',
            field=models.PositiveIntegerField(blank=True, help_text='Prix pro', null=True),
        ),
    ]
