# Generated by Django 6.0.4 on 2026-07-11 12:41

import django.core.validators
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formation', '0008_alter_formation_prix_etudiant_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscription',
            options={'ordering': ['-date_inscription']},
        ),
        migrations.AlterUniqueTogether(
            name='inscription',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Saisissez un numéro de téléphone valide.', regex='^\\+?[0-9][0-9 .()-]{6,19}$')]),
        ),
        migrations.AddConstraint(
            model_name='inscription',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), models.F('formation'), name='formation_email_inscription_unique'),
        ),
    ]
