# Generated by Django 6.0.4 on 2026-07-11 12:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formation', '0009_alter_inscription_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='prix_etudiant',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix étudiant', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='formation',
            name='prix_pro',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix pro', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
