# Generated by Django 6.0 on 2025-12-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('duree_heures', models.DecimalField(decimal_places=2, editable=False, max_digits=4)),
                ('montant_total', models.DecimalField(decimal_places=2, editable=False, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Réservation espace',
                'verbose_name_plural': 'Réservations espace',
                'ordering': ['-created_at'],
            },
        ),
    ]
