# Generated by Django 6.0.4 on 2026-07-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workspace', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reservationworkspace',
            constraint=models.CheckConstraint(condition=models.Q(('heure_fin__gt', models.F('heure_debut'))), name='workspace_fin_apres_debut'),
        ),
    ]
