# Generated by Django 6.0 on 2025-12-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boutique', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoarticle',
            name='image',
            field=models.ImageField(upload_to='photo_article'),
        ),
    ]
